[build]
  publish = "build"
  functions = "functions"  # 서버리스 함수 폴더 설정

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = true

[[edge_functions]]
  path = "/*"
  function = "hello-edge.js"  # 에지 함수 설정

[[headers]]
  for = "/index.html"
  [headers.values]
    X-Frame-Options = "DENY"
